const {
  mas,
  math,
  osep,
  jazs,
  fizi,
  ango,
  mnyi,
  halo,
  tori,
} = require("./links.js");

module.exports = {
  1: {
    1: {
      ora: "Matek",
      csoport: 3,
      k_ora: "8",
      k_perc: "0",
      link: math,
    },
    2: {
      ora: "Programozás Elmélet",
      csoport: 3,
      k_ora: "10",
      k_perc: "0",
      link: jazs,
    },
    3: {
      ora: "Programozás Gyakorlat",
      csoport: 1,
      k_ora: "11",
      k_perc: "0",
      link: osep,
    },
    4: {
      ora: "Programozás Gyakorlat",
      csoport: 2,
      k_ora: "11",
      k_perc: "0",
      link: jazs,
    },
    5: {
      ora: "Angol",
      csoport: 2,
      k_ora: "12",
      k_perc: "0",
      link: mas,
    },
  },
  2: {
    1: {
      ora: "Programozás Gyakorlat",
      csoport: 1,
      k_ora: "8",
      k_perc: "0",
      link: osep,
    },
    2: {
      ora: "Magyar nyelv és irodalom",
      csoport: 3,
      k_ora: "9",
      k_perc: "0",
      link: mnyi,
    },
    3: {
      ora: "Angol",
      csoport: 1,
      k_ora: "11",
      k_perc: "0",
      link: ango,
    },
    4: {
      ora: "Programozás Gyakorlat",
      csoport: 2,
      k_ora: "11",
      k_perc: "0",
      link: jazs,
    },
    5: {
      ora: "Történelem",
      csoport: 3,
      k_ora: "13",
      k_perc: "0",
      link: tori,
    },
  },
  3: {
    1: {
      ora: "Matek",
      csoport: 3,
      k_ora: "9",
      k_perc: "0",
      link: math,
    },
    2: {
      ora: "Magyar nyelv és irodalom",
      csoport: 3,
      k_ora: "10",
      k_perc: "0",
      link: mnyi,
    },
    3: {
      ora: "Fizika",
      csoport: 3,
      k_ora: "12",
      k_perc: "0",
      link: fizi,
    },
    4: {
      ora: "Programozás Gyakorlat",
      csoport: 1,
      k_ora: "13",
      k_perc: "0",
      link: osep,
    },
  },
  4: {
    1: {
      ora: "Programozás Gyakorlat",
      csoport: 1,
      k_ora: "9",
      k_perc: "0",
      link: osep,
    },
    2: {
      ora: "Programozás Gyakorlat",
      csoport: 2,
      k_ora: "8",
      k_perc: "0",
      link: jazs,
    },
    3: {
      ora: "Hálózat Gyakorlat",
      csoport: 3,
      k_ora: "10",
      k_perc: "0",
      link: halo,
    },
    4: {
      ora: "Angol",
      csoport: 1,
      k_ora: "12",
      k_perc: "0",
      link: ango,
    },
  },
  5: {
    1: {
      ora: "Hálózat Elmélet",
      csoport: 3,
      k_ora: "9",
      k_perc: "0",
      link: halo,
    },
    2: {
      ora: "Történelem",
      csoport: 3,
      k_ora: "10",
      k_perc: "0",
      link: tori,
    },
    3: {
      ora: "Programozás Gyakorlat",
      csoport: 1,
      k_ora: "12",
      k_perc: "0",
      link: osep,
    },
    4: {
      ora: "Angol",
      csoport: 2,
      k_ora: "12",
      k_perc: "0",
      link: mas,
    },
  },
};
